language: python
python:
  - 2.7
  - 3.3
  - 3.4
install:
    - pip install .
before_script:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
script: coverage run --source=flask_resize -m py.test
after_success:
    - coveralls
