language: python
sudo: false
cache: pip

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  - REQUIREMENTS=release
  - REQUIREMENTS=svg

install:
    - pip install tox

script:
    - tox -e py-$REQUIREMENTS

after_success:
    - coveralls
