language: python
sudo: false
cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
env:
  - WITH_SVG=0
  - WITH_SVG=1
install:
    - if [[ $WITH_SVG == '0' ]]; then pip install '.[test]'; fi
    - if [[ $WITH_SVG == '1' ]]; then pip install '.[svg,test]'; fi
script: coverage run --source=flask_resize -m py.test -v
after_success:
    - coveralls
